# ---
# ansible_ip: 109.94.208.172
# ansible_host: "ourvpn01.mnhycr.ru"
# ansible_port: 22
# ansible_user: drazin
# ansible_sudo_pass: "{{ vault_admin_password }}"
# ansible_ssh_pass: "{{ vault_admin_password }}"
# ansible_become: true

# dns_hostname: our-vpn
# packages:
#   - iftop
#   - htop
#   - curl
# users:
#   drazin: "{{ vault_drazin }}"

# # OpenVPN settings
# server_port: 1984
# server_name: "ourvpn01.mnhycr.ru"
# real_server_name: "ourvpn01.mnhycr.ru"
# dev_type: tun
# allow_masquerade: True
# additional_pushes:
#  - "redirect-gateway def1"
# vpn_network: 10.10.0.0
# vpn_netmask: 255.255.255.0
# vpn_cidr: 24
# dns_pushes:
#   - 8.8.8.8
#   - 8.8.4.4
# auth: SHA512
# cipher: AES-256-CBC
# keys_action: issue
# iptables_configure: True
# cert_prefix: "our_vpn_"
# use_ldap: False
# enable_logging: True

# enable_2fa: False
# client_2fa_server_description: OurVPN

# clients: "{{ vault_clients }}" 

# ------------------------------------
---
ansible_ip: 109.94.208.172
ansible_host: "ourvpn01.mnhycr.ru"
ansible_port: 22
ansible_user: drazin
ansible_sudo_pass: "{{ vault_admin_password }}"
ansible_ssh_pass: "{{ vault_admin_password }}"
ansible_become: true

dns_hostname: our-vpn
packages:
  - iftop
  - htop
  - curl
users:
  drazin: "{{ vault_drazin }}"

iptables:
  host_allowed_udp_ports: [1984]
  flush_all: no
  raw_rules:
    - "-P INPUT ACCEPT"
    - "-P FORWARD ACCEPT"
    - "-P OUTPUT  ACCEPT"

    - "-t nat -A POSTROUTING -s 10.10.0.0/24 -j MASQUERADE"

    - "-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT -m comment --comment 'accept-anything-already-accepted'"

    - "-A INPUT -i lo -j ACCEPT -m comment --comment 'accept-anything-on-the-loopback-interface'"

    - "-A INPUT -m state --state INVALID -j DROP -m comment --comment 'drop-invalid-packets'"

    - "-A INPUT -p udp --dport  500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"
    - "-A INPUT -p udp --dport 4500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"

    - "-A FORWARD --match policy --pol ipsec --dir in  --proto esp -s {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"
    - "-A FORWARD --match policy --pol ipsec --dir out --proto esp -d {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"

    - "-t mangle -A FORWARD --match policy --pol ipsec --dir in -s {{ ipsec_vpn_network }} -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360 -m comment --comment 'reduce-MTU/MSS-values-for-dumb-VPN-clients'"

    - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -m policy --pol ipsec --dir out -j ACCEPT -m comment --comment 'exempt-IPsec-traffic-from-masquerading'"
    - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -j MASQUERADE -m comment --comment 'masquerade-VPN-traffic-over-eth0-etc'"

    # - "-F"
    # - "-t nat -F"
    # - "-t mangle -F"

    # # # rate-limit repeated new requests from same IP to any ports
    # - "-I INPUT -m state --state NEW -m recent --set"
    # - "-I INPUT -m state --state NEW -m recent --update --seconds 300 --hitcount 60 -j DROP"

    # - "-A INPUT -p udp --dport  500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"
    # - "-A INPUT -p udp --dport 4500 -j ACCEPT -m comment --comment 'accept-IPSec/NAT-T-for-VPN'"

    # - "-A FORWARD --match policy --pol ipsec --dir in  --proto esp -s {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"
    # - "-A FORWARD --match policy --pol ipsec --dir out --proto esp -d {{ ipsec_vpn_network }} -j ACCEPT -m comment --comment 'forward-VPN-traffic-anywhere'"

    # - "-t mangle -A FORWARD --match policy --pol ipsec --dir in -s {{ ipsec_vpn_network }} -p tcp -m tcp --tcp-flags SYN,RST SYN -m tcpmss --mss 1361:1536 -j TCPMSS --set-mss 1360 -m comment --comment 'reduce-MTU/MSS-values-for-dumb-VPN-clients'"

    # - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -m policy --pol ipsec --dir out -j ACCEPT -m comment --comment 'exempt-IPsec-traffic-from-masquerading'"
    # - "-t nat -A POSTROUTING -s {{ ipsec_vpn_network }} -j MASQUERADE -m comment --comment 'masquerade-VPN-traffic-over-eth0-etc'"

    # - "-A INPUT   -j DROP -m comment --comment 'fall-through-to-drop-any-other-input-traffic'"
    # - "-A FORWARD -j DROP -m comment --comment 'fall-through-to-drop-any-other-forward-traffic'"

ipsec_server_name: ourvpn01.mnhycr.ru
ipsec_override_iptables: no
ipsec_vpn_network: 10.78.0.0/16
# ipsec_cert_path: "cert.pem"
ipsec_cert_path: "/etc/ipsec.d/certs/cert.pem"
# ipsec_cacert_path: "chain.pem"
ipsec_cacert_path: "/etc/ipsec.d/cacerts/ca.pem"
# ipsec_private_key_path: "private.pem"
ipsec_private_key_path: "/etc/ipsec.d/private/private.pem"
ipsec_clients: "{{ vault_ipsec_clients }}"
ipsec_private_key_type: ECDSA
ipsec_client_auth_type: "eap-mschapv2"

