---
ansible_ip: 192.168.1.170
ansible_host: 192.168.1.170
ansible_port: 22
ansible_user: xolog
ansible_sudo_pass: "{{ vault_admin_password }}"
ansible_ssh_pass: "{{ vault_admin_password }}"
ansible_become: true

packages:
  - atop
  - sysstat
  - iotop
  - iftop
  - git
  - curl

users:
  xolog: "{{ vault_xolog }}"

dns_hostname: personal_pi
