---
ansible_ip: 31.172.64.143
# ansible_host: "gateway.mnhycr.ru"
ansible_host: "31.172.64.143"
ansible_port: 22
ansible_user: drazin
ansible_sudo_pass: "{{ vault_admin_password }}" 
ansible_become: true

dns_hostname: gateway
packages:
  - iftop
  - htop
  - curl
users:
  drazin: "{{ vault_drazin }}"
