---
nginx_listen_port: 8888
nginx_volumes:
  - /etc/nginx:/etc/nginx

nginx_main_conf: |
  user  nginx;
  worker_processes  auto;

  error_log  /var/log/nginx/error.log notice;
  pid        /var/run/nginx.pid;

  worker_rlimit_nofile 65535;
  events {
      worker_connections  16384;
      multi_accept on;
      accept_mutex off;
  }

  timer_resolution 500ms;
  worker_priority -10;


  http {
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      tcp_nopush     on;
      tcp_nodelay on;
      aio threads;

      keepalive_timeout  65;

      include /etc/nginx/conf.d/*.conf;
  }

nginx_default_conf: |
  server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location /.well-known/matrix/client {
      default_type application/json;
      return 200 '{ "m.homeserver": { "base_url": "https://social.mnhycr.ru" },"org.matrix.msc2965.authentication": { "issuer": "https://social.mnhycr.ru/","account": "https://social.mnhycr.ru/account" } }';
    }

    location /.well-known/matrix/server {
      default_type application/json;
      return 200 '{ "m.server": "https://social.mnhycr.ru" }';
    }
  }
