---
certbot_auto_renew: true
certbot_auto_renew_user: mnhycr
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: true
certbot_create_method: standalone
certbot_admin_email: one.914.mind@gmail.com

# Default webroot, overwritten by individual per-cert webroot directories
certbot_webroot: /var/www/letsencrypt

certbot_certs: 
  - domains:
      - nextcloud.mnhycr.ru
  - domains:
      - deluge.mnhycr.ru
  - domains:
      - bitwarden.mnhycr.ru
  - domains:
      - plex.mnhycr.ru
  - domains:
      - files.mnhycr.ru
  - domains:
      - mnhycr.ru

# Available options: 'package', 'snap', 'source'.
certbot_install_method: 'package'
