---
ansible_ip: 192.168.0.101
ansible_host: 192.168.0.101
ansible_port: 22
ansible_user: mnhycr
ansible_sudo_pass: "{{ vault_admin_password }}"
ansible_ssh_pass: "{{ vault_admin_password }}"
ansible_become: true

packages:
  - atop
  - sysstat
  - iotop
  - iftop
  - python
  - git
  - curl

users:
  mnhycr: "{{ vault_mnhycr }}"
