---
ansible_ip: 31.172.74.115
ansible_host: ourvpn.mnhycr.ru 
ansible_port: 22
ansible_user: drazin
ansible_sudo_pass: "{{ vault_admin_password }}"
ansible_become: true

dns_hostname: ourvpn
packages:
  - iftop
  - htop
  - curl
users:
  drazin: "{{ vault_drazin }}"
