---
ansible_ip: 91.224.87.6
# ansible_host: "gateway.mnhycr.ru"
ansible_host: "91.224.87.6"
ansible_port: 22
ansible_user: drazin
ansible_sudo_pass: "{{ vault_admin_password }}" 
ansible_become: true

dns_hostname: gateway
packages:
  - iftop
  - htop
  - curl
users:
  drazin: "{{ vault_drazin }}"
